### ISSUE TITLE
Crash report delete some file

### ISSUE THREAD

**Issue by Shopimisrel** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#135]
## Exception
* __App Name:__ Amaze - כלי עזר לקבצים
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.71
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ a12s
* __Model:__ SM-A127F
* __Product:__ a12snnxx
<details><summary><b>Crash log </b></summary>

```
java.lang.NullPointerException
	at q3.a$a.invoke(AbstractMediaFileInfoOperationsFragment.kt:10)
	at u2.c.onClick(Unknown Source:3)
	at androidx.appcompat.app.AlertController$c.handleMessage(AlertController.java:3)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

**Comment by LWWRS88** [comment]
> ## Issue explanation (write below this line)
> 
> 
> 
> ## Exception
> * __App Name:__ Amaze - כלי עזר לקבצים
> * __Package:__ com.amaze.fileutilities
> * __Version:__ 1.71
> * __User Action:__ UI Error
> * __Request:__ Application crash
> * __OS:__ Linux Android 12 - 31
> * __Device:__ a12s
> * __Model:__ SM-A127F
> * __Product:__ a12snnxx
> <details><summary><b>Crash log </b></summary>
> 
> ```
> java.lang.NullPointerException
> 	at q3.a$a.invoke(AbstractMediaFileInfoOperationsFragment.kt:10)
> 	at u2.c.onClick(Unknown Source:3)
> 	at androidx.appcompat.app.AlertController$c.handleMessage(AlertController.java:3)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:313)
> 	at android.app.ActivityThread.main(ActivityThread.java:8669)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
> 
> ```
> </details>
> <hr>
> 

https://github.com/TeamAmaze/AmazeFileUtilities-Issue-Tracker/issues/135

**Comment by LWWRS88** [comment]
> ## Issue explanation (write below this line)
> 
> 
> 
> ## Exception
> * __App Name:__ Amaze - כלי עזר לקבצים
> * __Package:__ com.amaze.fileutilities
> * __Version:__ 1.71
> * __User Action:__ UI Error
> * __Request:__ Application crash
> * __OS:__ Linux Android 12 - 31
> * __Device:__ a12s
> * __Model:__ SM-A127F
> * __Product:__ a12snnxx
> <details><summary><b>Crash log </b></summary>
> 
> ```
> java.lang.NullPointerException
> 	at q3.a$a.invoke(AbstractMediaFileInfoOperationsFragment.kt:10)
> 	at u2.c.onClick(Unknown Source:3)
> 	at androidx.appcompat.app.AlertController$c.handleMessage(AlertController.java:3)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:313)
> 	at android.app.ActivityThread.main(ActivityThread.java:8669)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
> 
> ```
> </details>
> <hr>
>
