### ISSUE TITLE
FR: Music thumbnails

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#14]
Show music thumbnails here👇🏿

![IMG_20220421_234801_879](https://user-images.githubusercontent.com/48226312/164527029-36fed78d-fe55-4a36-af1b-a7abedab7b9d.jpg)

Plus on notification bar

![IMG_20220421_234904_183](https://user-images.githubusercontent.com/48226312/164527206-b66525a0-3e79-4e21-bff3-dbdccb47043f.jpg)

**Comment by VishalNehra** [comment]
fixed with v1.43

**Comment by shuvashish76** [comment]
No notification thumbnail.

App version: 1.44
Android version: 8.1.0
