### ISSUE TITLE
Startup flashing

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#16]
- Just like Amaze, show initial startup flash as Black for FU _(I know the white flash is my android8 issue)_

Or use banner as discussed here: https://github.com/TeamAmaze/AmazeFileManager/discussions/3137#discussioncomment-2026499

**Comment by VishalNehra** [comment]
White flash isn't just android 8 issue, it happens for my android 11 as well. That's a theme issue. I tried fixing it for utils but it has many other components that starts breaking if i use the fix that's in amaze fm.
I'll try fixing this again because it's annoying for me as well.

**Comment by VishalNehra** [comment]
fixed with 1.39
