### ISSUE TITLE
Images : Delete option "Not allowed"

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#5]
![Screenshot_2022-04-13-03-55-59](https://user-images.githubusercontent.com/48226312/163065474-83598808-0caa-45ed-a07d-569cc9bcb4c1.jpeg)

Image location : Device Internal storage

App version: **1.14 (15)**

**Comment by VishalNehra** [comment]
fixed in 1.16+
