### ISSUE TITLE
[QUESTION] Do you plan on making the app open source in the future?

### ISSUE THREAD

**Issue by PassionateG1t** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#89]
Is this something you intend on doing? Just like the File Manager.

**Comment by VishalNehra** [comment]
Sure, this discussion is pending. Currently we need funds for team to function and for Amaze File Manager's continued development (we have rewards and bounties for issues and fixes). 
Amaze Utilities is one of the major medium for these funds.
Also, currently this software is in initial stage, i.e. it isn't much famous and has less downloads. As soon as we make it open source someone else might remove trial based code and make it completely free and publish on Play Store. Their free version will become more famous than our paid version.
So the idea is to hold on till X downloads before we make it open source. As well as for continued development for Amaze File Manager itself.

Till then, we might look at other license options that allow giving source code to people who pay for software but they aren't allowed to publish their version of it anywhere.

**Comment by ivosm** [comment]
It looks nice, but wouldn't be possible in the meantime to avoid the necessity of Google play, i.e. pay for it through a different channel? 
PS: As a long time x-plore user, Amaze is really not bad (x-plore is still more graphically lucid) and no-google wold be a huge benefit.

**Comment by VishalNehra** [comment]
Sorry for not updating here. This app is already open source, and is available on fdroid as well. If you don't plan to pay through Google, you can download fdroid version and donate us through different channels

https://github.com/TeamAmaze/AmazeFileUtilities

**Comment by ivosm** [comment]
Thanks.
